#ifndef DEPENDS_QT_H
#define DEPENDS_QT_H

#include <QApplication>
#include <QtGui>
#include <QtPlugin>
#include <QMainWindow>
#include <QFrame>
#include <QDialog>
#include <QMessageBox>
#include <QMenu>
#include <QMenuBar>
#include <QToolBar>
#include <QtextCodec>
#include <QStyle>
#include <QDesktopWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QToolBar>
#include <QTableView>
#include <QScrollArea>
#include <QComboBox>
#include <QTextEdit>
#include <QPushButton>
#include <QRadioButton>
#include <QCheckBox>
#include <QHeaderView>
#include <QMessageBox>
#include <QDebug>
#include <QDialogButtonBox>
#include <QFileDialog>
#include <QFile>
#include <QDate>
#include <QList>
#include <QByteArray>
#include <QString>
#include <QStringList>
#include <QtextStream>
#include <QTimer>
#include <QSplitter>
#include <QGroupBox>
#include <QListWidget>
#include <QScrollArea>
#include <QLineEdit>
#include <QTabWidget>
#include <QTextEdit>
#include <QTextBrowser>
#include <QSpacerItem>
#include <QLabel>
#include <QToolButton>
#include <QDoubleSpinBox>
#include <QScrollBar>
#include <cmath>
#include <QtCore/qmath.h>
#include <QIcon>


#endif // DEPENDS_QT_H
